# Generated by Django 5.0 on 2024-01-12 09:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_post_author_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default=None, null=True
            ),
        ),
    ]
