# Generated by Django 5.0 on 2024-01-12 10:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="", null=True
            ),
        ),
    ]
