# Generated by Django 5.0 on 2024-01-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
