# Generated by Django 5.0.1 on 2024-01-11 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_alter_comment_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="title",
        ),
    ]
