# Generated by Django 5.0 on 2024-01-11 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_alter_comment_author_alter_comment_post"),
        ("comments", "0004_alter_comment_author"),
    ]

    operations = []
