# Generated by Django 5.0 on 2024-01-12 10:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0005_merge_20240111_1043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default="", null=True
            ),
        ),
    ]
