# Generated by Django 5.0.1 on 2024-01-12 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0005_merge_20240111_1043"),
        ("comments", "0005_remove_comment_title"),
    ]

    operations = []
