# Generated by Django 5.0 on 2024-01-12 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0006_alter_comment_content"),
        ("comments", "0006_merge_20240112_0925"),
    ]

    operations = []
