# Generated by Django 5.0.1 on 2024-01-12 11:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0006_merge_20240112_0925"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, max_length=500
            ),
        ),
    ]
