# Generated by Django 5.0 on 2024-01-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0007_merge_20240112_1032"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
