# Generated by Django 5.0 on 2024-01-12 10:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0008_comment_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="title",
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default=""
            ),
        ),
    ]
