# Generated by Django 5.0 on 2024-01-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "categories",
            "0002_alter_category_options_alter_maincategory_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
