# Generated by Django 5.0 on 2024-01-06 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_category_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="maincategory",
            old_name="name",
            new_name="title",
        ),
    ]
