# Generated by Django 5.0 on 2024-01-11 00:54


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_rename_name_category_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="main_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="categories.maincategory",
            ),
        ),
    ]
