name: Python CI

on: [push]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run mypy
      run: mypy .

    - name: Run black
      run: black --check .

    - name: Run isort
      run: isort --check-only .

    - name: Check coverage
      run: |
        coverage run -m pytest
        coverage report --fail-under=80
        coverage xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
