name: Python CI

on: [push]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy black isort 

    - name: Run mypy
      run: mypy .

    - name: Run black
      run: black --check .

    - name: Run isort
      run: isort --check-only .